name: Artifact

on: [push]

env:
   ARTIFACT_NAME: myartifact1

jobs:
   main:
      runs-on: ubuntu-latest
      steps:
        - name: Check out the code
          uses: actions/checkout@v4.2.2
        - name: Upload the artifact
          uses: actions/upload-artifact@v4.6.2
          with:
            name: ${{ env.ARTIFACT_NAME }}
            path: .
